### ISSUE TITLE
[Bug] Sliding after a fall roll glitches you in a place

### ISSUE THREAD

**Issue by xdoxx123** [JonnyBro/beatrun#226] opened 2024-12-18 18:04 UTC
**Describe the bug**
So if you slide after rolling you just glitch in place and even R wont save ya

**To Reproduce**
1. Go on a high surface with a landing space
2. When you jump down hold ctrl
3. wait till you roll and slide
4. be stuck

**Expected behavior**
i expected for it to just slide make me able to jump back and run

**Screenshots/Videos**
i dont have any :(

**Additional information:**
 - Game Version: x64 / chromium
- Game Type: Singleplayer

**Additional context**
No addons that conflict

**Comment by relaxtakenotes** [comment] 2024-12-20 08:00
run Beatrun_DebugToggle next time it happens

**Comment by xdoxx123** [comment] 2024-12-20 15:18
here 
![20241220161737_1](https://github.com/user-attachments/assets/61f8ba68-725d-4278-bc2f-8d69a1b8f21d)

**Comment by relaxtakenotes** [comment] 2024-12-20 15:31
well that's awesome, it doesn't tell me much sadly. could you record a video with cl_showpos 2 next?

**Comment by relaxtakenotes** [comment] 2024-12-20 16:33
okay, update beatrun, and then proceed to do the same things i've told you to do, along with running Beatrun_DebugToggle before playing. i added some debug stuff that will help me figure things out
![gmod_gHeNOFBEK3](https://github.com/user-attachments/assets/20326b82-c2dc-48bd-8a0e-019645b6483a)

**Comment by xdoxx123** [comment] 2024-12-20 17:00
Uploading 2024-12-20 17-56-38.mp4…

**Comment by xdoxx123** [comment] 2024-12-20 17:00
https://github.com/user-attachments/assets/a5b145d3-08ef-4619-b567-39546590d9ef

**Comment by relaxtakenotes** [comment] 2024-12-20 17:44
> @relaxtakenotes

yeah, i've seen the report. please try the new update now

**Comment by xdoxx123** [comment] 2024-12-20 18:35
> > @relaxtakenotes
> 
> yeah, i've seen the report. please try the new update now

it still is glitched with the update

**Comment by relaxtakenotes** [comment] 2024-12-20 18:55
That's unfortunate. Will try more things tomorrow

**Comment by relaxtakenotes** [comment] 2024-12-21 09:57
try the newest version

**Comment by chupapimunyanyu** [comment] 2024-12-22 02:13
still bugged :(

**Comment by relaxtakenotes** [comment] 2024-12-22 10:23
would anyone be willing to let me remote into their pc's, so i can figure out what exactly is being broken? the problem is that i am unable to reproduce this bug on my machine under any circumstances, so i need access to someone's game where the issue does indeed happen

**Comment by relaxtakenotes** [comment] 2024-12-22 11:05
eh but before that try the new update again

**Comment by chupapimunyanyu** [comment] 2024-12-22 11:22
ayy it is fixed now! thank you

**Comment by relaxtakenotes** [comment] 2024-12-22 12:01
https://www.youtube.com/watch?v=jYRKvdEJSJc

**Closed by relaxtakenotes** 2024-12-22 12:01 UTC
Labels: bug
