### ISSUE TITLE
[Bug] Softlock when mantling to a corner

### ISSUE THREAD

**Issue by RedyRT** [JonnyBro/beatrun#33] opened 2023-07-18 17:27 UTC
**Describe the bug**
Softlock when mantling to a corner, only CTRL button works and nothing else. Check video

**To Reproduce**
1. Go to 'this map https://steamcommunity.com/sharedfiles/filedetails/?id=2876266251'
2. Click on 'subscribe'
3. Scroll down to 'my video and reproduce my moves'

**Expected behavior**
You will be softlocked if you do mantle to a corner like in the video

**Screenshots/Videos**
[2023-07-18 20-14-38.webm](https://github.com/JonnyBro/beatrun/assets/64935439/0e5abc4c-71f5-43b0-a57d-feb3d18f2df3)

**Additional information:**
 - Game Version: [chromium x64]
- Game Type: [singleplayer]

**Additional context**
_

**Comment by skozzu** [comment] 2023-07-19 06:33
that usually happens on some maps, like catalyst blockout, etc

**Comment by JonnyBro** [comment] 2023-07-21 17:32
Can you jump off it?

**Comment by RedyRT** [comment] 2023-07-21 20:56
> Can you jump off it?

CTRL works to jump off but in these situations like here you probably will be dead, it supposed to go up when i press W key, but its not working, thats what i mean

**Comment by RedyRT** [comment] 2023-07-21 21:30
I also got a new footage of this after updating:
[2023-07-22 00-18-53 (1).webm](https://github.com/JonnyBro/beatrun/assets/64935439/8295b0e2-94a9-49f7-aace-fe0a3d19eabd)
And also i caught a random bug in this video lol

**Comment by RedyRT** [comment] 2023-07-21 21:43
> I also got a new footage of this after updating: [2023-07-22 00-18-53 (1).webm](https://github.com/JonnyBro/beatrun/assets/64935439/8295b0e2-94a9-49f7-aace-fe0a3d19eabd) (with visible keys) And also i caught a random bug in this video lol

[2023-07-22 00-38-20.webm](https://github.com/JonnyBro/beatrun/assets/64935439/213749e7-273e-42b4-a365-343a3d58f649)

Bug with mantling animation i guess, just found it accidentally

**Comment by JonnyBro** [comment] 2023-07-22 05:11
> > I also got a new footage of this after updating: [2023-07-22 00-18-53 (1).webm](https://github.com/JonnyBro/beatrun/assets/64935439/8295b0e2-94a9-49f7-aace-fe0a3d19eabd) (with visible keys) And also i caught a random bug in this video lol
> 
>  2023-07-22.00-38-20.webm 
> Bug with mantling animation i guess, just found it accidentally

Yea, this should be fixed with latest update, forgot to bring back 1 line when I was testing

**Comment by JonnyBro** [comment] 2023-07-22 06:40
You can jump off of it in any direction with Space but not climb up

**Comment by JonnyBro** [comment] 2023-07-22 08:32
Found what the issue is, I just need to think about proper way to find a place to move player to after climbing

**Comment by RedyRT** [comment] 2023-07-22 12:39
> 

Yea, thats what i tried to say

**Comment by RedyRT** [comment] 2023-07-22 12:39
> Found what the issue is, I just need to think about proper way to find a place to move player to after climbing. It happens because mod can't find a place where it can place the player after climbing, I want to make a simple system to scan for the place and not just one

Yea, thats what i tried to say

**Closed** 2023-09-30 18:57 UTC
Labels: bug, in work, known
